### ISSUE TITLE
Error when running tools/init.

### ISSUE THREAD

**Issue by Glinkis** [alexjoverm/typescript-library-starter#141]
I got this error after I cloned the repo and ran `npm install`.

> --libraryname--@0.0.0 postinstall /Users/Victor/typescript-library-starter
> ts-node tools/init

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/Victor/typescript-library-starter/node_modules/replace-in-file/index.js:1:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by alexjoverm** [comment]
I couldn't reproduce this issue, can you try again with the latest version? If that doesn't work, please reopen providing more info of your system
