### ISSUE TITLE
Can't commit with Node 10 due to lint-staged dep on please-upgrade-node

### ISSUE THREAD

**Issue by mattmazzola** [alexjoverm/typescript-library-starter#220]
Steps to reproduce:
```bash
git clone https://github.com/alexjoverm/typescript-library-starter.git commit-error
cd commit-error
git add .
git commit -m "Initial Commit"
```
You'll see error:
```
"C:\Program Files\Git\bin\git.exe" commit -F "E:\Repos\commit-error\.git\COMMITMESSAGE"
husky > npm run -s precommit (node v10.0.0)

lint-staged requires at least version 6 of Node, please upgrade

husky > pre-commit hook failed (add --no-verify to bypass)
Done

Press Enter or Esc to close console...
```

There is incorrect node version detection which makes it think you're running version less than 6 even though it's greater....

See:
https://github.com/okonet/lint-staged/issues/432

Fix from that issue appears to be to update lint-staged to ^7.1.0.  The package.json defaults to ^7.0.0 but the package-lock.json keeps it at 7.0.0.

```
npm view lint-staged dist-tags
{ latest: '7.1.3' }
```

I thought this fix would be to simply update `lint-staged` to latest but that doesn't seem to work either, now I get error message complaining about needing greater than Node 4 🤣 .

![image](https://user-images.githubusercontent.com/2856501/40895725-de5a90ca-6765-11e8-9013-ecac5cd3c3ec.png)

**Comment by sudo-suhas** [comment]
@mattmazzola I found the fix for this issue. `prettier` actually bundles all dependencies and it was using an older version of `cosmiconfig` with the buggy dep `please-upgrade-node`. I edited the binary to use `console.trace`:

```
typescript-library-starter on  master [+] is 📦 v0.0.0 via ⬢ v10.3.0 
➜ ./node_modules/.bin/lint-staged
 ❯ Running tasks for {src,test}/**/*.ts
   ✖ prettier --write
     git add
✖ "prettier --write" found some errors. Please fix them and try committing again.

Trace: cosmiconfig requires at least version 4 of Node, please upgrade
at index$46 (/home/suhaskaranth/dev/playground/typescript-library-starter/node_modules/prettier/bin/prettier.js:7142:13)
at Object.<anonymous> (/home/suhaskaranth/dev/playground/typescript-library-starter/node_modules/prettier/bin/prettier.js:12523:1)
at Module._compile (internal/modules/cjs/loader.js:702:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
at Module.load (internal/modules/cjs/loader.js:612:32)
at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
at Function.Module._load (internal/modules/cjs/loader.js:543:3)
at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
at startup (internal/bootstrap/node.js:238:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
```

So `npm i prettier` updates it to the latest version and fixes the issue.
