### ISSUE TITLE
`Error: '__spreadArrays' is not exported by tslib` occurs when `npm run build`

### ISSUE THREAD

**Issue by Gr8tMiller** [alexjoverm/typescript-library-starter#310]
Hi, I got an error when `npm run build`, the message shown has nothing to do with my source code. 
```
(!) Error when using sourcemap for reporting an error: Can't resolve original location of error.
src/Row.ts: (1:43)
[!] Error: '__spreadArrays' is not exported by tslib
https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
src/Row.ts (1:43)
1: import {Cell} from './Cell';
                                 ^
2: import {Table} from './Table';
3: import {Column} from './Column';
Error: '__spreadArrays' is not exported by tslib
    at error (/Users/xxx/Workspace/projects/mytable/node_modules/rollup/dist/rollup.js:3460:30)
    at Module.error (/Users/xxx/Workspace/projects/mytable/node_modules/rollup/dist/rollup.js:13350:9)
    at handleMissingExport (/Users/xxx/Workspace/projects/mytable/node_modules/rollup/dist/rollup.js:13040:21)
    at Module.traceVariable (/Users/xxx/Workspace/projects/mytable/node_modules/rollup/dist/rollup.js:13454:17)
    at ModuleScope.findVariable (/Users/xxx/Workspace/projects/mytable/node_modules/rollup/dist/rollup.js:12726:29)
    at FunctionScope.Scope.findVariable (/Users/xxx/Workspace/projects/mytable/node_modules/rollup/dist/rollup.js:4022:68)
    at Scope.findVariable (/Users/xxx/Workspace/projects/mytable/node_modules/rollup/dist/rollup.js:4022:68)
    at FunctionScope.Scope.findVariable (/Users/xxx/Workspace/projects/mytable/node_modules/rollup/dist/rollup.js:4022:68)
    at Scope.findVariable (/Users/xxx/Workspace/projects/mytable/node_modules/rollup/dist/rollup.js:4022:68)
    at Identifier$$1.bind (/Users/xxx/Workspace/projects/mytable/node_modules/rollup/dist/rollup.js:10111:40)
```
these are all modules I added in my project:
```
  "devDependencies": {
    // ...
    "rollup-plugin-less": "latest"
  },
  "dependencies": {
    "handsontable": "^6.2.2",
    "lodash": "^4.17.11",
    "nanobus": "^4.4.0",
    "uuid": "^3.3.2"
  }
```
the complete log is [here](https://github.com/alexjoverm/typescript-library-starter/files/3663705/mytable.log)

i would really appreciate it if you can help me.

**Comment by Gr8tMiller** [comment]
my fault, adding 
```
"importHelpers": true,
```
into `tsconfig.json` fix the problem.
refer https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by mjcc007** [comment]
I have the same problem！  how did you resolved it？

**Comment by yiliang114** [comment]
the same problem

**Comment by GooGee** [comment]
update devDependencies

```
"rollup-plugin-typescript2": "^0.23.0"
```

**Comment by benxaamin** [comment]
Also you need to bump the rollup version in devDependencies

```
"rollup": "^0.68.0"
```

**Comment by SammyRobensParadise** [comment]
Just as an update was experiencing this same issue again with:
```
"rollup-plugin-typescript2": "^0.29.0",
"rollup": "^2.38.5",
```
Bumping to v0.30.0 solved the issue.
```
"rollup-plugin-typescript2": "^0.30.0"
```

**Comment by NadaTO** [comment]
if you are working with react app in typescript you may just need to install "tslib"  to solve the problem.
====> npm install tslib

tslib will then be added to your package.json

**Comment by jhunexjun** [comment]
Solved this by `npm install tslib@latest --save`
